# This is just meant to be a random string that can be used to identify _your server_ specifically.
# This is currently set manually but later it will be given to you _from_ Cerberus for you to put here.
authorization: ""
